### ISSUE TITLE
Only first statefulset created when spinning up new cluster

### ISSUE THREAD

**Issue by rocket357** [cscetbon/casskop#83]
## Type of question

General Help

## Question

**What did you do?**
Fresh install (via helm3) of casskop 2.1.13 in GKE (v1.22.15-gke.100) I see the following logged repeatedly:

```
time="2022-12-20T20:22:14Z" level=info msg="Error Waiting for sts change" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
1.6715677348775537e+09  INFO    controller_cassandracluster     Reconciling CassandraCluster    {"Request.Namespace": "development", "Request.Name": "sre-cassandra"}
time="2022-12-20T20:22:14Z" level=info msg="We will request : sre-cassandra-srecassandra100g-uscentral1a-0.sre-cassandra to catch hostIdMap" cluster=sre-cassandra err="<nil>"
time="2022-12-20T20:22:14Z" level=info msg="The Operator Waits 20 seconds for the action to start correctly" cluster=sre-cassandra rack=srecassandra100g-uscentral1a
time="2022-12-20T20:22:16Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:17Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:18Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:19Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:20Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:20Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:20Z" level=info msg="Error Waiting for sts change" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-20T20:22:20Z" level=error msg="Issue when updating CassandraCluster" cluster=sre-cassandra err="Operation cannot be fulfilled on cassandraclusters.db.orange.com \"sre-cassandra\": the object has been modified; please apply your changes to the latest version and try again"
1.6715677400486872e+09  INFO    controller_cassandracluster     Reconciling CassandraCluster    {"Request.Namespace": "development", "Request.Name": "sre-cassandra"}
time="2022-12-20T20:22:20Z" level=info msg="We will request : sre-cassandra-srecassandra100g-uscentral1a-0.sre-cassandra to catch hostIdMap" cluster=sre-cassandra err="<nil>"
time="2022-12-20T20:22:20Z" level=info msg="The Operator Waits 20 seconds for the action to start correctly" cluster=sre-cassandra rack=srecassandra100g-uscentral1a
```

This results in only the first statefulset being created, as the operator hangs indefinitely waiting for the sts change.

**What did you expect to see?**
I expected to see the cluster spin up completely with all "racks/statefulsets" coming online.

**What did you see instead? Under which circumstances?**
The operator hangs waiting for an unknown statefulset update to take place, causing only one rack to come online.

**Environment**
* casskop version:

2.1.13

* Kubernetes version information:

 kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:07:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15-gke.100", GitCommit:"4262ac74f84d8f8ec8f692ea2080483e932554f9", GitTreeState:"clean", BuildDate:"2022-09-22T09:24:03Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE

* Cassandra version:

3.11.14

**Comment by rocket357** [comment]
I tested this morning on 2.1.12 and got the same results. I wasn't able to test on 2.1.11 or 2.1.10 due to images not being found properly (a fresh install was looking for tag 1.0.0 on both?).

Testing on 2.1.9 currently and I'll report back.

**Comment by cscetbon** [comment]
@rocket357  Can you test with Cassandra 3.11.9 ? Our e2e tests run with this version with no issue https://github.com/cscetbon/casskop/blob/master/test/kuttl/sidecars/00-clusterWithTwoSidecars.yaml#L7. I'd like to see if it's because of the version of Cassandra for some reason

**Comment by rocket357** [comment]
Certainly, testing now.

**Comment by rocket357** [comment]
Same behavior observed with Cassandra 3.11.9 on fresh 2.1.13 helm install.

```
time="2022-12-23T18:50:19Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:20Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:21Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:22Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:23Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:23Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:23Z" level=info msg="Error Waiting for sts change" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
1.6718214236750228e+09  INFO    controller_cassandracluster     Reconciling CassandraCluster    {"Request.Namespace": "development", "Request.Name": "sre-cassandra"}
time="2022-12-23T18:50:23Z" level=info msg="We will request : sre-cassandra-srecassandra100g-uscentral1a-0.sre-cassandra to catch hostIdMap" cluster=sre-cassandra err="<nil>"
time="2022-12-23T18:50:23Z" level=info msg="[sre-cassandra][srecassandra100g-uscentral1a]: Update UpdateStatefulSet is Done"
time="2022-12-23T18:50:24Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:25Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:26Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:27Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:28Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:28Z" level=info msg="Waiting for new version of statefulset" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:28Z" level=info msg="Error Waiting for sts change" cluster=sre-cassandra statefulset=sre-cassandra-srecassandra100g-uscentral1a
time="2022-12-23T18:50:28Z" level=error msg="Issue when updating CassandraCluster" cluster=sre-cassandra err="Operation cannot be fulfilled on cassandraclusters.db.orange.com \"sre-cassandra\": the object has been modified; please apply your changes to the latest version and try again"
```

**Comment by cscetbon** [comment]
Interesting .... Our tests run with 1.20.15 see https://github.com/cscetbon/casskop/blob/master/.github/workflows/e2e-tests.yml#L101. If you can test with a similar version as well. There might something with the k8s version used :/

**Comment by cscetbon** [comment]
@rocket357 👆

**Comment by rocket357** [comment]
I don't have the means to test on 1.20 currently due to some other projects that have come up.  I'll re-open (or re-create) in the future once I get a moment.

**Comment by ajoskowski** [comment]
I encountered on the same problem when I tried to upgrade casskop from 2.1.10 to 2.1.16.
In operator I see the same logs like @rocket357 but I see also problems in cassandra pod:
```
WARN  [cassandra-exporter-harvester-defer-0] 2023-05-15 11:57:24,295 Harvester.java:188 - Failed to register collector for MBean org.apache.cassandra.metrics:type=Connection,scope=10.244.8.21,name=SmallMessageCompletedTasks
java.lang.IllegalStateException: Object NamedObject{name=org.apache.cassandra.metrics:type=Connection,scope=10.244.8.21,name=SmallMessageCompletedTasks, object=org.apache.cassandra.metrics.CassandraMetricsRegistry$JmxGauge@437eada4} and NamedObject{name=org.apache.cassandra.metrics:type=Connection,scope=10.244.8.21,name=SmallMessageCompletedTasks, object=org.apache.cassandra.metrics.CassandraMetricsRegistry$JmxGauge@e0d8bc6} cannot be merged, yet their labels are the same.
    at com.zegelin.cassandra.exporter.collector.dynamic.FunctionalMetricFamilyCollector.lambda$merge$0(FunctionalMetricFamilyCollector.java:73) ~[cassandra-exporter-agent.jar:na]
    at java.util.HashMap.merge(HashMap.java:1254) ~[na:1.8.0_282]
    at com.zegelin.cassandra.exporter.collector.dynamic.FunctionalMetricFamilyCollector.merge(FunctionalMetricFamilyCollector.java:73) ~[cassandra-exporter-agent.jar:na]
    at java.util.HashMap.merge(HashMap.java:1254) ~[na:1.8.0_282]
    at java.util.Collections$SynchronizedMap.merge(Collections.java:2689) ~[na:1.8.0_282]
    at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:184) ~[cassandra-exporter-agent.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_282]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_282]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_282]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_282]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_282]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_282]
```
I see the same results for cassandra `3.11.9` and `3.11.14`.

**Comment by ajoskowski** [comment]
@cscetbon Can you reopen this issue?
